apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: server
        image: recommendationservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: FLAGD_HOST
          value: "flagd"
        - name: FLAGD_PORT
          value: "8013"
        - name: FLAGD_TIMEOUT_SECONDS
          value: "10"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
